services:
  backend:
    build: .
    ports:
      - 3000:3000
    env_file: .env
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - URL=http://0.0.0.0:3000
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
  
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: